# Name of workflow
name: Lint and tests

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: install deps
        run: |
          bun install
        env:
          CI: true
      - name: Run formatter
        run: |
          bun run fmt
      - name: Run linter
        run: |
          bun run lint
      - name: Test & publish code coverage
        run: |
          bun run test
